version: '3'

services:
  client:
    build: ./client
    ports:
      - "8080:8080"
      - "4343:4343"
    depends_on:
      - server
    volumes:
      - ./client:/usr/src/client
  server:
    build: ./server
    ports:
      - "5000:5000"
    volumes:
      - ./server:/usr/src/server
